
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mixins]]
    config = "${mod_name}.mixins.json"
[[mixins]]
    config = "${mod_name}.mixins-common.json"

[[mods]]
    modId = "sawmill"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon="minecraft:brush" #catalogue icon

[[dependencies.sawmill]]
    modId = "forge"
    type = "REQUIRED"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.sawmill]]
    modId = "minecraft"
    type = "REQUIRED"
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "BOTH"


[[dependencies.sawmill]]
    modId = "moonlight"
    type = "REQUIRED"
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
