
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"


[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}-common.mixins.json"


[[mods]]
    modId = "sawmill"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon = "minecraft:brush" #catalogue icon

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "BOTH"


[[dependencies.sawmill]]
    modId = "moonlight"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
